/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Spacesuit.gltf -o src/components/Spacesuit.jsx -r public
*/

// Model from Quaternius: https://quaternius.com/packs/ultimatemodularcharacters.html

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";

export function Spacesuit(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/Spacesuit.gltf");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["Gun_Shoot"].fadeIn(0.5).play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="SpaceSuit_Body">
            <skinnedMesh
              name="Cube002"
              geometry={nodes.Cube002.geometry}
              material={materials.SciFi_Light}
              skeleton={nodes.Cube002.skeleton}
            />
            <skinnedMesh
              name="Cube002_1"
              geometry={nodes.Cube002_1.geometry}
              material={materials.SciFi_Light_Accent}
              skeleton={nodes.Cube002_1.skeleton}
            />
            <skinnedMesh
              name="Cube002_2"
              geometry={nodes.Cube002_2.geometry}
              material={materials.SciFi_Main}
              skeleton={nodes.Cube002_2.skeleton}
            />
            <skinnedMesh
              name="Cube002_3"
              geometry={nodes.Cube002_3.geometry}
              material={materials.SciFi_MainDark}
              skeleton={nodes.Cube002_3.skeleton}
            />
          </group>
          <group name="SpaceSuit_Feet">
            <skinnedMesh
              name="Cube047"
              geometry={nodes.Cube047.geometry}
              material={materials.SciFi_Light_Accent}
              skeleton={nodes.Cube047.skeleton}
            />
            <skinnedMesh
              name="Cube047_1"
              geometry={nodes.Cube047_1.geometry}
              material={materials.SciFi_Light}
              skeleton={nodes.Cube047_1.skeleton}
            />
          </group>
          <group name="SpaceSuit_Head">
            <skinnedMesh
              name="Cube049"
              geometry={nodes.Cube049.geometry}
              material={materials.SciFi_Light}
              skeleton={nodes.Cube049.skeleton}
            />
            <skinnedMesh
              name="Cube049_1"
              geometry={nodes.Cube049_1.geometry}
              material={materials.SciFi_Light_Accent}
              skeleton={nodes.Cube049_1.skeleton}
            />
            <skinnedMesh
              name="Cube049_2"
              geometry={nodes.Cube049_2.geometry}
              material={materials.Grey}
              skeleton={nodes.Cube049_2.skeleton}
            />
          </group>
          <group name="SpaceSuit_Legs">
            <skinnedMesh
              name="Cube046"
              geometry={nodes.Cube046.geometry}
              material={materials.SciFi_Main}
              skeleton={nodes.Cube046.skeleton}
            />
            <skinnedMesh
              name="Cube046_1"
              geometry={nodes.Cube046_1.geometry}
              material={materials.SciFi_Light}
              skeleton={nodes.Cube046_1.skeleton}
            />
            <skinnedMesh
              name="Cube046_2"
              geometry={nodes.Cube046_2.geometry}
              material={materials.SciFi_Light_Accent}
              skeleton={nodes.Cube046_2.skeleton}
            />
            <skinnedMesh
              name="Cube046_3"
              geometry={nodes.Cube046_3.geometry}
              material={materials.SciFi_MainDark}
              skeleton={nodes.Cube046_3.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Spacesuit.gltf");
