/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Couch Small.glb -o src/components/CouchSmall.jsx -r public
Couch Small by Quaternius (https://poly.pizza/m/ZOPP3KzNIk)
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function CouchSmall(props) {
  const { nodes, materials } = useGLTF("/models/Couch Small.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh
          geometry={nodes.Couch_Small1_1.geometry}
          material={materials.Couch_Blue}
        />
        <mesh
          geometry={nodes.Couch_Small1_2.geometry}
          material={materials.Black}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Couch Small.glb");
