/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Palm tree.glb -o src/components/PalmTree.jsx -r public
Palm tree by jeremy [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/bjGeBbKhAVN)
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function PalmTree(props) {
  const { nodes, materials } = useGLTF("/models/Palm tree.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["palm_tree_01-Mesh"].geometry}
        material={materials["795548"]}
      />
      <mesh
        geometry={nodes["palm_tree_01-Mesh_1"].geometry}
        material={materials["8BC34A"]}
      />
      <mesh
        geometry={nodes["palm_tree_01-Mesh_2"].geometry}
        material={materials.DD9944}
      />
    </group>
  );
}

useGLTF.preload("/models/Palm tree.glb");
