/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Casual_Hoodie.gltf -o src/components/Casual_Hoodie.jsx -r public
*/

// Model from Quaternius: https://quaternius.com/packs/ultimatemodularcharacters.html

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef } from "react";

export function CasualHoodie(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/Casual_Hoodie.gltf"
  );
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Run_Back"].fadeIn(0.5).play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Casual_Body">
            <skinnedMesh
              name="Cube008"
              geometry={nodes.Cube008.geometry}
              material={materials.Skin}
              skeleton={nodes.Cube008.skeleton}
            />
            <skinnedMesh
              name="Cube008_1"
              geometry={nodes.Cube008_1.geometry}
              material={materials.Purple}
              skeleton={nodes.Cube008_1.skeleton}
            />
          </group>
          <group name="Casual_Feet">
            <skinnedMesh
              name="Cube000"
              geometry={nodes.Cube000.geometry}
              material={materials.Purple}
              skeleton={nodes.Cube000.skeleton}
            />
            <skinnedMesh
              name="Cube000_1"
              geometry={nodes.Cube000_1.geometry}
              material={materials.White}
              skeleton={nodes.Cube000_1.skeleton}
            />
          </group>
          <group name="Casual_Head">
            <skinnedMesh
              name="Cube014"
              geometry={nodes.Cube014.geometry}
              material={materials.Skin}
              skeleton={nodes.Cube014.skeleton}
            />
            <skinnedMesh
              name="Cube014_1"
              geometry={nodes.Cube014_1.geometry}
              material={materials.Eyebrows}
              skeleton={nodes.Cube014_1.skeleton}
            />
            <skinnedMesh
              name="Cube014_2"
              geometry={nodes.Cube014_2.geometry}
              material={materials.Eye}
              skeleton={nodes.Cube014_2.skeleton}
            />
            <skinnedMesh
              name="Cube014_3"
              geometry={nodes.Cube014_3.geometry}
              material={materials.Hair}
              skeleton={nodes.Cube014_3.skeleton}
            />
          </group>
          <group name="Casual_Legs">
            <skinnedMesh
              name="Cube005"
              geometry={nodes.Cube005.geometry}
              material={materials.Skin}
              skeleton={nodes.Cube005.skeleton}
            />
            <skinnedMesh
              name="Cube005_1"
              geometry={nodes.Cube005_1.geometry}
              material={materials.LightBlue}
              skeleton={nodes.Cube005_1.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Casual_Hoodie.gltf");
