/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/breakroom.gltf -o src/components/breakroom.jsx -r public 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function breakroom(props) {
  const { nodes, materials } = useGLTF("/models/breakroom.gltf");
  return (
    <group {...props} dispose={null}>
      <group
        position={[581.743, 315.882, -374.091]}
        rotation={[-Math.PI / 2, 0, -0.005]}
        scale={2.54}
      >
        <group position={[4.861, 0.229, -6.884]}>
          <mesh
            geometry={nodes.Box087.geometry}
            material={materials["03 - Default.001"]}
            position={[0.275, 0, -1.764]}
            scale={0.954}
          />
          <mesh
            geometry={nodes.Box088.geometry}
            material={materials["Material #109.001"]}
            position={[-41.326, 0, -1.772]}
          />
          <mesh
            geometry={nodes.Box089.geometry}
            material={materials["15 - Default.001"]}
            position={[-41.482, 0, -1.772]}
          />
        </group>
        <group position={[4.861, 0.229, 18.97]}>
          <mesh
            geometry={nodes.Box090.geometry}
            material={materials["03 - Default.001"]}
            position={[0.275, 0, -1.764]}
            scale={0.954}
          />
          <mesh
            geometry={nodes.Box091.geometry}
            material={materials["Material #109.001"]}
            position={[-41.326, 0, -1.772]}
          />
          <mesh
            geometry={nodes.Box092.geometry}
            material={materials["15 - Default.001"]}
            position={[-41.482, 0, -1.772]}
          />
        </group>
        <group position={[4.861, 0.229, 44.824]}>
          <mesh
            geometry={nodes.Box093.geometry}
            material={materials["03 - Default.001"]}
            position={[0.275, 0, -1.764]}
            scale={0.954}
          />
          <mesh
            geometry={nodes.Box094.geometry}
            material={materials["Material #109.001"]}
            position={[-41.326, 0, -1.772]}
          />
          <mesh
            geometry={nodes.Box095.geometry}
            material={materials["15 - Default.001"]}
            position={[-41.482, 0, -1.772]}
          />
        </group>
        <mesh
          geometry={nodes.Box074.geometry}
          material={nodes.Box074.material}
          position={[5.161, 50.585, -128.146]}
        />
        <mesh
          geometry={nodes.Box075.geometry}
          material={materials["Material #109.001"]}
          position={[5.199, 1.134, 127.701]}
        />
        <mesh
          geometry={nodes.Box076.geometry}
          material={materials["Material #109.001"]}
          position={[5.199, 47.982, 127.701]}
        />
        <mesh
          geometry={nodes.Box077.geometry}
          material={materials["03 - Default.001"]}
          position={[46.456, 1.135, 125.648]}
          scale={0.973}
        />
        <mesh
          geometry={nodes.Box078.geometry}
          material={materials["03 - Default.001"]}
          position={[5.014, 0.229, -127.734]}
        />
        <mesh
          geometry={nodes.Box079.geometry}
          material={materials["Material #109.001"]}
          position={[5.199, -48.179, 127.701]}
          rotation={[0, 0, Math.PI]}
        />
        <mesh
          geometry={nodes.Box080.geometry}
          material={materials["03 - Default.001"]}
          position={[5.199, 1.134, 89.365]}
          scale={0.981}
        />
        <mesh
          geometry={nodes.Cylinder115.geometry}
          material={materials["Material #109.001"]}
          position={[-17.292, 116.732, -124.363]}
          scale={[1.231, 1, 1]}
        />
        <group position={[-28.364, 7.592, -84.254]} scale={0.502}>
          <mesh
            geometry={nodes.Mesh502.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh502_1.geometry}
            material={materials["Material #136.001"]}
          />
        </group>
        <group
          position={[-27.981, -2.122, -84.254]}
          rotation={[0, 0, 2.531]}
          scale={0.502}
        >
          <mesh
            geometry={nodes.Mesh503.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh503_1.geometry}
            material={materials["Material #111.001"]}
          />
        </group>
        <mesh
          geometry={nodes.Box096.geometry}
          material={materials["15 - Default.001"]}
          position={[5.199, 45.292, 123.748]}
          scale={0.945}
        />
        <mesh
          geometry={nodes.Box097.geometry}
          material={materials["15 - Default.001"]}
          position={[5.199, -46.314, 123.748]}
          rotation={[0, 0, Math.PI]}
          scale={0.937}
        />
        <mesh
          geometry={nodes.Box084.geometry}
          material={materials["03 - Default.001"]}
          position={[5.136, 0.229, -34.501]}
          scale={0.954}
        />
        <mesh
          geometry={nodes.Box085.geometry}
          material={materials["Material #109.001"]}
          position={[-36.465, 0.229, -34.509]}
        />
        <mesh
          geometry={nodes.Box086.geometry}
          material={materials["15 - Default.001"]}
          position={[-36.622, 0.229, -34.509]}
        />
        <mesh
          geometry={nodes.Box081.geometry}
          material={materials["03 - Default.001"]}
          position={[5.136, 0.229, -61.061]}
          scale={0.954}
        />
        <mesh
          geometry={nodes.Box082.geometry}
          material={materials["Material #109.001"]}
          position={[-36.465, 0.229, -61.069]}
        />
        <mesh
          geometry={nodes.Box083.geometry}
          material={materials["15 - Default.001"]}
          position={[-36.622, 0.229, -61.069]}
        />
        <group position={[-28.364, 16.938, -84.254]} scale={0.502}>
          <mesh
            geometry={nodes.Mesh542.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh542_1.geometry}
            material={materials["Material #136.001"]}
          />
        </group>
        <group position={[-28.364, 26.283, -84.254]} scale={0.502}>
          <mesh
            geometry={nodes.Mesh543.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh543_1.geometry}
            material={materials["Material #136.001"]}
          />
        </group>
        <group position={[-28.364, 35.629, -84.254]} scale={0.502}>
          <mesh
            geometry={nodes.Mesh544.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh544_1.geometry}
            material={materials["Material #136.001"]}
          />
        </group>
        <group
          position={[-27.981, -31.534, -84.254]}
          rotation={[0, 0, 2.531]}
          scale={0.502}
        >
          <mesh
            geometry={nodes.Mesh551.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh551_1.geometry}
            material={materials["Material #111.001"]}
          />
        </group>
        <group position={[-28.364, 7.592, -59.069]} scale={0.502}>
          <mesh
            geometry={nodes.Mesh557.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh557_1.geometry}
            material={materials["Material #136.001"]}
          />
        </group>
        <group position={[-28.364, 16.938, -59.069]} scale={0.502}>
          <mesh
            geometry={nodes.Mesh559.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh559_1.geometry}
            material={materials["Material #136.001"]}
          />
        </group>
        <group position={[-28.364, 35.629, -59.069]} scale={0.502}>
          <mesh
            geometry={nodes.Mesh561.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh561_1.geometry}
            material={materials["Material #136.001"]}
          />
        </group>
        <group
          position={[-27.981, -21.73, -59.069]}
          rotation={[0, 0, 2.531]}
          scale={0.502}
        >
          <mesh
            geometry={nodes.Mesh567.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh567_1.geometry}
            material={materials["Material #111.001"]}
          />
        </group>
        <group
          position={[-27.981, -31.534, -59.069]}
          rotation={[0, 0, 2.531]}
          scale={0.502}
        >
          <mesh
            geometry={nodes.Mesh568.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh568_1.geometry}
            material={materials["Material #111.001"]}
          />
        </group>
        <group
          position={[-27.981, -2.122, -32.084]}
          rotation={[0, 0, 2.531]}
          scale={0.502}
        >
          <mesh
            geometry={nodes.Mesh575.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh575_1.geometry}
            material={materials["Material #111.001"]}
          />
        </group>
        <group position={[-28.364, 26.283, -32.084]} scale={0.502}>
          <mesh
            geometry={nodes.Mesh577.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh577_1.geometry}
            material={materials["Material #136.001"]}
          />
        </group>
        <group position={[-28.364, 35.629, -32.084]} scale={0.502}>
          <mesh
            geometry={nodes.Mesh578.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh578_1.geometry}
            material={materials["Material #136.001"]}
          />
        </group>
        <group position={[-28.364, 7.592, -6.387]} scale={0.502}>
          <mesh
            geometry={nodes.Mesh591.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh591_1.geometry}
            material={materials["Material #136.001"]}
          />
        </group>
        <group position={[-28.364, 26.283, -6.387]} scale={0.502}>
          <mesh
            geometry={nodes.Mesh594.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh594_1.geometry}
            material={materials["Material #136.001"]}
          />
        </group>
        <group position={[-28.364, 35.629, -6.387]} scale={0.502}>
          <mesh
            geometry={nodes.Mesh595.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh595_1.geometry}
            material={materials["Material #136.001"]}
          />
        </group>
        <group
          position={[-27.981, -11.926, -6.387]}
          rotation={[0, 0, 2.531]}
          scale={0.502}
        >
          <mesh
            geometry={nodes.Mesh600.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh600_1.geometry}
            material={materials["Material #111.001"]}
          />
        </group>
        <group
          position={[-27.981, -2.122, 19.041]}
          rotation={[0, 0, 2.531]}
          scale={0.502}
        >
          <mesh
            geometry={nodes.Mesh609.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh609_1.geometry}
            material={materials["Material #111.001"]}
          />
        </group>
        <group
          position={[-27.981, -31.534, 19.041]}
          rotation={[0, 0, 2.531]}
          scale={0.502}
        >
          <mesh
            geometry={nodes.Mesh619.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh619_1.geometry}
            material={materials["Material #111.001"]}
          />
        </group>
        <group position={[-28.364, 7.592, 45.211]} scale={0.502}>
          <mesh
            geometry={nodes.Mesh625.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh625_1.geometry}
            material={materials["Material #136.001"]}
          />
        </group>
        <group position={[-28.364, 35.629, 45.211]} scale={0.502}>
          <mesh
            geometry={nodes.Mesh629.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh629_1.geometry}
            material={materials["Material #136.001"]}
          />
        </group>
        <group
          position={[-27.981, -21.73, 45.211]}
          rotation={[0, 0, 2.531]}
          scale={0.502}
        >
          <mesh
            geometry={nodes.Mesh635.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh635_1.geometry}
            material={materials["Material #111.001"]}
          />
        </group>
        <group
          position={[-27.981, -31.534, 45.211]}
          rotation={[0, 0, 2.531]}
          scale={0.502}
        >
          <mesh
            geometry={nodes.Mesh636.geometry}
            material={materials["Material #26.001"]}
          />
          <mesh
            geometry={nodes.Mesh636_1.geometry}
            material={materials["Material #111.001"]}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.Box098.geometry}
        material={nodes.Box098.material}
        position={[1009.07, 0, -386.21]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[2.54, 9.276, 2.54]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[-361.447, 0, -384.574]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.34, 10.29, 2.54]}
      />
    </group>
  );
}

useGLTF.preload("/models/breakroom.gltf");
