/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Duck.gltf -o src/components/Duck.jsx -r public
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Duck(props) {
  const { nodes, materials } = useGLTF("/models/Duck.gltf");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.character_duck.geometry}
        material={materials["White.026"]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <mesh
          geometry={nodes.character_duckArmLeft.geometry}
          material={materials["White.026"]}
          position={[0.204, 0, -0.634]}
        />
        <mesh
          geometry={nodes.character_duckArmRight.geometry}
          material={materials["White.026"]}
          position={[-0.204, 0, -0.634]}
        />
        <group position={[0, 0, -0.704]}>
          <mesh
            geometry={nodes.Cube1338.geometry}
            material={materials["White.026"]}
          />
          <mesh
            geometry={nodes.Cube1338_1.geometry}
            material={materials["Yellow.043"]}
          />
          <mesh
            geometry={nodes.Cube1338_2.geometry}
            material={materials["Black.027"]}
          />
        </group>
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/Duck.gltf");
