/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Panda.gltf -o src/components/Panda.jsx -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React, { useEffect, useRef, useState } from "react";

export function Panda(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/Panda.gltf");
  const { actions } = useAnimations(animations, group);
  const [animation, setAnimation] = useState("Chop_Loop");
  useEffect(() => {
    actions[animation].fadeIn(0.5).play();
    return () => actions[animation].fadeOut(0.5);
  }, [animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <skinnedMesh
            name="Headband"
            geometry={nodes.Headband.geometry}
            material={materials.Atlas}
            skeleton={nodes.Headband.skeleton}
          />
          <skinnedMesh
            name="Knife"
            geometry={nodes.Knife.geometry}
            material={materials.Atlas}
            skeleton={nodes.Knife.skeleton}
          />
          {/* <skinnedMesh
            name="Pan"
            geometry={nodes.Pan.geometry}
            material={materials.Atlas}
            skeleton={nodes.Pan.skeleton}
          /> */}
          <skinnedMesh
            name="Panda"
            geometry={nodes.Panda.geometry}
            material={materials.Atlas}
            skeleton={nodes.Panda.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Panda.gltf");
