/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Lighthouse.glb
*/

// Lighthouse scene by Poly by Google [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/1O6BWfUB6ta)

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Lighthouse(props) {
  const { nodes, materials } = useGLTF("models/Lighthouse.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Lighthouse.geometry}
        material={materials.lambert2SG}
      />
    </group>
  );
}

useGLTF.preload("models/Lighthouse.glb");
